"""Import the workflow gaps of every product as `gap` needs.

Usage: import_gaps.py [--site build/site] [--output docs/_global/gaps.rst]

Reads build/site/<product>/gaps.json (`ubc agent gaps`, written by
tools/build_product.sh after configuring the product) and writes one `gap`
need per gap and product, inside an `if` block for that product:
  GAP_<need id>_<link>__<PRODUCT>, gap_for the need, fields gap_category,
  gap_link, gap_shortfall, gap_need_id, gap_need_type, product.
Imported BMS needs are exempt (status imported) and never appear here.
The output is a committed snapshot; re-run after tools/build_all.sh.
"""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LINKS = {"traces_to", "satisfies", "refines", "implements", "verifies", "results_for", "affects",
         "motivates", "mitigates", "gap_for", "allocates", "links"}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--site", type=Path, default=ROOT / "build/site")
    ap.add_argument("--output", type=Path, default=ROOT / "docs/_global/gaps.rst")
    args = ap.parse_args()
    out = [
        "Workflow gaps",
        "=============",
        "",
        "Workflow gaps (``gap``) of each product, generated by",
        "``tools/import_gaps.py`` from ``ubc agent gaps``. Only the gaps of this",
        "build's product (:variant:`meta.product`) are shown.",
        "",
        ".. needtable::",
        "   :types: gap",
        "   :columns: id, gap_category, gap_for, gap_shortfall",
        "   :style: table",
    ]
    total = 0
    for site in sorted(p for p in args.site.iterdir() if (p / "gaps.json").exists()):
        product = site.name
        gaps = json.loads((site / "gaps.json").read_text())["gaps"]
        block = []
        count = 0
        for g in gaps:
            if g["id"].startswith(("BMS_", "GAP_")):
                continue
            link = g.get("link") if g.get("link") in LINKS else ""
            suffix = (g.get("link") or g["category"]).upper()
            count += 1
            block += [
                "",
                f"   .. gap:: {g['id']}: {g['category']} {g.get('link', '')}".rstrip(),
                f"      :id: GAP_{g['id']}_{suffix}__{product.upper()}",
                f"      :gap_for: {g['id']}",
                f"      :gap_category: {g['category']}",
                f"      :gap_link: {link}",
                f"      :gap_shortfall: {g.get('have', 0)} of {g.get('need', 1)}",
                f"      :gap_need_id: {g['id']}",
                f"      :gap_need_type: {g['type']}",
                f"      :product: {product}",
                "",
                f"      ``ubc agent gaps`` reports {g['id']} ({g['type']}) in {product}.",
            ]
        total += count
        if block:
            out += ["", f".. if:: var.meta.product == '{product}'", *block]
    args.output.write_text("\n".join(out) + "\n")
    print(f"import_gaps: {total} gaps written to {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
